### ISSUE TITLE
Fine tuning LLM models for education

### ISSUE THREAD

**Issue by Rzz8** [teacheraide/moodle-local_teacheraide#42]
Investigate relavent Australia Secondary Education data and fine tuning LLM models

**Comment by ycfreeman** [comment]
would probably be good to explore different base models as well

**Comment by ycfreeman** [comment]
but we can limit it to text -> text models for now

**Comment by ycfreeman** [comment]
more points to think about:
- where to run / host the model
  - do we use a service or do we host our own
- self tuning?

**Comment by Rzz8** [comment]
> possible technical challenges, that may or may not affect how and where we tune the model
> 
> * where to run / host the model
>   
>   * do we use a service or do we host our own in a custom cloud workload
>   *    For testing purpose, we run locally. Later we deploy it to the cloud.
> * self tuning? or pre-train and upload?
> *      Early stage we can take some pre-trained model(s). Later I can tune a base model from Hugging Face using additional data.
